[[redirects]]
  from = "/currency/*"
  to = "https://keen-haibt-ecf9f4.netlify.app/currency/:splat"
  status = 200
  force = true
 
[[redirects]]
  from = "/albertcss/*"
  to = "https://nifty-turing-6bafb1.netlify.app/albertcss/:splat"
  status = 200
  force = true
